services:
  - type: web
    name: elite-homes-api
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
